name: medical_clinic_team13
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter_bloc: ^8.1.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
     - family: OleoScriptSwashCaps
       fonts:
         - asset: assets/fonts
           style: italic
     - family: Trajan Pro
       fonts:
         - asset: assets/fonts
           weight: 400
